#!/bin/bash
container_name = $1
if [ -z $1 ]
then
  echo "1.luweiss-docker-lnmp-mysql80"
  echo "2.luweiss-docker-lnmp-php72-fpm"
  echo "3.luweiss-docker-lnmp-nginx"
  read -p "请输入您需要连接的容器[1～3]:" input
  echo $input
	  case $input in
	  1) container_name="luweiss-docker-lnmp-mysql80";;
	  2) container_name="luweiss-docker-lnmp-php72-fpm";;
	  3) container_name="luweiss-docker-lnmp-nginx";;
	  esac
fi
docker exec -it $container_name /bin/bash
